In [1]:
import numpy as np
import pandas as pd

In [2]:
# Collections - List, Tuples, Dictionaries, Set (Array --- Python Implementation (Heavy memory and is not optimized))
# Numpy - Optimized Arrays (1D array (Scalar) , 2D array (Vector), n-dimensional array)
# Mathematical computation

onedimarray = np.array([1,2,3,4,5])

In [3]:
onedimarray

array([1, 2, 3, 4, 5])

In [4]:
onedimarray.shape #Defines the type of array 1d,2d , 3d etc
#In this case its a 1 D array, Scalar

(5,)

In [5]:
twodimarray = np.array([[1,2],[3,4]]) #Matrix of 2X2
twodimarray

array([[1, 2],
       [3, 4]])

In [6]:
twodimarray.shape

(2, 2)

In [7]:
#benefits of numpy --- Mathematical calc
resultArray = onedimarray + onedimarray

In [8]:
resultArray

array([ 2,  4,  6,  8, 10])

In [9]:
resultArray2d = twodimarray + twodimarray

In [11]:
resultArray2d

array([[2, 4],
       [6, 8]])

In [12]:
resultArray2d2 = twodimarray * twodimarray
resultArray2d2

array([[ 1,  4],
       [ 9, 16]])

In [18]:
#Pandas - Data Analysis library, Data Manipulation library, Viz
#Loaded a data without header
employee = pd.read_csv('E:\\DataScienceSL\\MachineLearningSection\\MLMorningBatch\\employee.csv' , header=None , names=['eid','ename','esal'])

In [19]:
employee # Represented in the form of DataFrames (Table)

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [22]:
#In the world of Pandas, dataframe is nothing but set of Series
print(type(employee['eid']))
print(employee['eid']) # Scalar

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
Name: eid, dtype: int64


In [23]:
# Whenever you work with Pandas, it's mandatory to import numpy.
# All the mathematical operation that is supported by Pandas requires numpy packages.

In [24]:
#dataset with header
employeeHeaders = pd.read_csv('employeeWithHeaders.csv')

In [25]:
employeeHeaders

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [31]:
#Pandas
# Task - Create a new column called yearlySalary . Compute yearlySalary using esal.
yearlySalary = employee.esal * 12 
print(yearlySalary)
print(type(yearlySalary))

0     12000
1     24000
2     24000
3    118536
4    119988
Name: esal, dtype: int64
<class 'pandas.core.series.Series'>


In [32]:
#Add extra column
employee['yearlySalary'] = yearlySalary
employee

eid     ename  esal  yearlySalary
0    1  Prashant  1000         12000
1    2      Amar  2000         24000
2    3    Chitra  2000         24000
3    4  Utkarsha  9878        118536
4    5      Ajit  9999        119988

In [33]:
# employee['result']=employee.eid + employee.esal

In [34]:
# Use function in pandas
# Another use-case
# Incrementing the salary based on given below conditions
# 1. sal is less than equal to 2000, inc by 10%
# 2. sal is between 2001 and 8999, inc by 5%
# 3. sal is above 8999, no inc

def increMent(sal):
    result = 0
    if sal <= 2000:
        result = sal + (sal * 0.1)
        return result
    elif sal >= 2001 and sal <= 8999:
        result = sal + (sal * 0.05)
        return result
    else:
        return sal


In [35]:
#Apply function on a column(series)
#apply method

employee['NewSalary'] = employee.esal.apply(increMent)
employee

eid     ename  esal  yearlySalary  NewSalary
0    1  Prashant  1000         12000     1100.0
1    2      Amar  2000         24000     2200.0
2    3    Chitra  2000         24000     2200.0
3    4  Utkarsha  9878        118536     9878.0
4    5      Ajit  9999        119988     9999.0

In [38]:
#traversing
# Create another dataframe named resultDf which holds ename and NewSalary from employee DF. (index location iloc)
# iloc[records,columns]
resultDF = employee.iloc[:,[1,4]]
resultDF

ename  NewSalary
0  Prashant     1100.0
1      Amar     2200.0
2    Chitra     2200.0
3  Utkarsha     9878.0
4      Ajit     9999.0

In [39]:
resultDF = employee.iloc[[0,2,4],[1,4]]
resultDF

ename  NewSalary
0  Prashant     1100.0
2    Chitra     2200.0
4      Ajit     9999.0

In [40]:
employee

eid     ename  esal  yearlySalary  NewSalary
0    1  Prashant  1000         12000     1100.0
1    2      Amar  2000         24000     2200.0
2    3    Chitra  2000         24000     2200.0
3    4  Utkarsha  9878        118536     9878.0
4    5      Ajit  9999        119988     9999.0

In [44]:
#range
# startindex,upperbound ---------> upperbound = endindex + 1
resultDF = employee.iloc[2:4,1:3]
resultDF

ename  esal
2    Chitra  2000
3  Utkarsha  9878

In [47]:
#how to filter based on condition?
#Filter those employees whose salary is greater than 6000
employee[employee.esal >= 6000]

eid     ename  esal  yearlySalary  NewSalary
3    4  Utkarsha  9878        118536     9878.0
4    5      Ajit  9999        119988     9999.0

In [48]:
#performing join
department = pd.read_csv('departments.csv')

In [49]:
department

eid    deptname
0    1  Operations
1    2          HR
2    3     Finance
3    4  Operations
4    5          HR

In [50]:
employee

eid     ename  esal  yearlySalary  NewSalary
0    1  Prashant  1000         12000     1100.0
1    2      Amar  2000         24000     2200.0
2    3    Chitra  2000         24000     2200.0
3    4  Utkarsha  9878        118536     9878.0
4    5      Ajit  9999        119988     9999.0

In [61]:
finalDF = pd.merge(employee,department, on = 'eid') #Inner join
finalDF

eid     ename  esal  yearlySalary  NewSalary    deptname
0    1  Prashant  1000         12000     1100.0  Operations
1    2      Amar  2000         24000     2200.0          HR
2    3    Chitra  2000         24000     2200.0     Finance
3    4  Utkarsha  9878        118536     9878.0  Operations
4    5      Ajit  9999        119988     9999.0          HR

In [65]:
finalDF = finalDF.drop([3] , axis = 0) # row

In [68]:
finalDF = finalDF.drop('deptname', axis = 1)  # column

In [69]:
finalDF

eid     ename  esal  yearlySalary  NewSalary
0    1  Prashant  1000         12000     1100.0
1    2      Amar  2000         24000     2200.0
2    3    Chitra  2000         24000     2200.0

In [78]:
def updateSal(df,eid1,sal):
    if df.eid == eid1:
        df['esal'] = sal

In [79]:
updateSal(employee,3,5000)
employee

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().